#!/usr/bin/env node
/**
 * npm run build:content
 *
 * Reads database/content-source.cjs and writes:
 *   src/content/defaults.json            (website fallback content)
 *   database/migration-03-content.sql    (the same content, for Supabase)
 *
 * Edit content-source.cjs, never the two outputs.
 */
const fs = require("fs");
const path = require("path");
const { PAGES, FAQ_CATEGORIES, FAQS, SERVICES, SETTINGS } = require("./content-source.cjs");

const ROOT = path.join(__dirname, "..");
const q = (value) => `'${String(value ?? "").replace(/'/g, "''")}'`;
const j = (value) => `${q(JSON.stringify(value ?? null))}::jsonb`;

/* ---------- normalise ---------- */
const pages = PAGES.map((page) => ({
  path: page.path,
  label: page.label,
  group: page.group,
  published: page.published !== false,
  seo: page.seo || {},
  sections: page.sections.map((s, index) => ({
    key: s.key,
    label: s.label || s.key,
    type: s.type,
    eyebrow: s.eyebrow || "",
    title: s.title || "",
    subtitle: s.subtitle || "",
    body: s.body || "",
    items: (s.items || []).map((it) => ({ title: it.title || "", body: it.body || "", image: it.image || "" })),
    media_url: s.media_url || "",
    video_url: s.video_url || "",
    cta_label: s.cta_label || "",
    cta_href: s.cta_href || "",
    settings: s.settings || {},
    enabled: s.enabled !== false,
    position: index,
  })),
}));

// sanity checks — fail loudly rather than emit something broken
const seen = new Set();
for (const page of pages) {
  if (seen.has(page.path)) throw new Error(`duplicate page ${page.path}`);
  seen.add(page.path);
  const keys = new Set();
  for (const s of page.sections) {
    if (keys.has(s.key)) throw new Error(`duplicate section key ${page.path}#${s.key}`);
    keys.add(s.key);
    if (!s.type) throw new Error(`section without type ${page.path}#${s.key}`);
  }
}

/* ---------- JSON for the website ---------- */
const json = {
  generated: "database/build-content.cjs — do not edit by hand",
  pages: Object.fromEntries(pages.map((p) => [p.path, { label: p.label, group: p.group, published: p.published, seo: p.seo, sections: p.sections }])),
  registry: pages.map((p) => ({ path: p.path, label: p.label, group: p.group })),
  faqCategories: FAQ_CATEGORIES,
  faqs: FAQS,
  services: SERVICES,
};
fs.mkdirSync(path.join(ROOT, "src/content"), { recursive: true });
fs.writeFileSync(path.join(ROOT, "src/content/defaults.json"), JSON.stringify(json, null, 1) + "\n");

/* ---------- legacy keys: the 91 sections seeded by migration-01 ---------- */
const seedSql = fs.readFileSync(path.join(__dirname, "seed.sql"), "utf8");
const legacyPairs = [...new Set(
  [...seedSql.matchAll(/\('(\/[a-z-]*)', '[^']*', '([a-z0-9-]+)'/g)].map((m) => `${m[1]}|${m[2]}`)
)].map((s) => s.split("|"));
const legacyFaqs = [...new Set(
  [...seedSql.matchAll(/insert into public\.faqs[^\n]*\nselect id, '((?:[^']|'')*)'/g)].map((m) => m[1].replace(/''/g, "'"))
)];

/* ---------- SQL ---------- */
const out = [];
const w = (s = "") => out.push(s);

w("-- ============================================================================");
w("--  SIRAJ BUILDERS — MIGRATION 03: DOCUMENTED CONTENT");
w("--  GENERATED by database/build-content.cjs from database/content-source.cjs.");
w("--  Do not edit by hand — edit content-source.cjs and run `npm run build:content`.");
w("--  ----------------------------------------------------------------------------");
w("--  Run AFTER migration-02-cms.sql. Safe to run more than once.");
w("--");
w("--  What it does — and what it will NOT touch:");
w("--    * Page sections: replaces ONLY the sections seeded by the previous");
w("--      release that nobody has edited since (updated_at = created_at).");
w("--      Anything an admin edited or created is kept exactly as it is.");
w("--    * FAQs: replaces only the old seeded questions nobody edited, then adds");
w("--      the 20 documented questions. [TO CONFIRM] ones arrive unpublished,");
w("--      with no answer, for the admin to complete.");
w("--    * Services, pages, settings: fills BLANK fields only.");
w("-- ============================================================================");
w();
w("begin;");
w();
w("-- 1. Remove unedited legacy sections -------------------------------------");
w("delete from public.page_sections s");
w("using (values");
w(legacyPairs.map(([p, k]) => `  (${q(p)}, ${q(k)})`).join(",\n"));
w(") as legacy(page_path, section_key)");
w("where s.page_path = legacy.page_path");
w("  and s.section_key = legacy.section_key");
w("  and s.updated_at = s.created_at;");
w();
w("-- 2. Insert documented sections (existing keys are left alone) ----------");
w("insert into public.page_sections");
w("  (page_path, page_label, section_key, label, section_type, eyebrow, title, subtitle, body, items, media_url, video_url, cta_label, cta_href, settings, position, is_enabled)");
w("values");
const rows = [];
for (const page of pages) {
  for (const s of page.sections) {
    rows.push(`  (${[q(page.path), q(page.label), q(s.key), q(s.label), q(s.type), q(s.eyebrow), q(s.title), q(s.subtitle), q(s.body), j(s.items), q(s.media_url), q(s.video_url), q(s.cta_label), q(s.cta_href), j(s.settings), s.position, s.enabled].join(", ")})`);
  }
}
w(rows.join(",\n"));
w("on conflict (page_path, section_key) do nothing;");
w();
w("-- 3. Kept (edited) sections: fill empty list items / images from the docs");
for (const page of pages) {
  for (const s of page.sections) {
    if (s.items.length) {
      w(`update public.page_sections set items = ${j(s.items)} where page_path = ${q(page.path)} and section_key = ${q(s.key)} and (items is null or items = '[]'::jsonb);`);
    }
  }
}
w();
w("-- 3b. Editorial media: fill only blank fields that an admin has not overridden");
for (const page of pages) {
  for (const s of page.sections) {
    for (const field of ["media_url", "video_url"]) {
      if (!s[field]) continue;
      w(`update public.page_sections set ${field} = ${q(s[field])}`);
      w(` where page_path = ${q(page.path)} and section_key = ${q(s.key)}`);
      w(`   and coalesce(${field}, '') = ''`);
      w(`   and coalesce(settings->'editor_overrides'->>${q(field)}, 'false') <> 'true';`);
    }
  }
}
w();
w("-- 4. Old 'Page copy' edits carried into the new hero sections ------------");
w("update public.page_sections s");
w("   set title = p.title,");
w("       body = coalesce(nullif(p.intro, ''), s.body),");
w("       media_url = coalesce(nullif(p.image_url, ''), s.media_url)");
w("  from public.pages p");
w(" where p.path = s.page_path");
w("   and s.section_key = 'hero'");
w("   and s.updated_at = s.created_at");
w("   and p.updated_at > p.created_at + interval '2 seconds'");
w("   and nullif(trim(p.title), '') is not null;");
w();
w("-- 5. Pages registry: publish state for unconfirmed services --------------");
const unpublished = pages.filter((p) => !p.published).map((p) => q(p.path));
w(`update public.pages set is_published = false where path in (${unpublished.join(", ")}) and updated_at = created_at;`);
w();
w("-- 6. Pages registry: one row per route, SEO filled where blank -----------");
w("insert into public.pages (path, label, eyebrow, title, seo_title, seo_description, is_published, sort_order)");
w("values");
w(pages.map((p, i) => `  (${[q(p.path), q(p.label), q(p.label), q(p.label), q(p.seo.title || ""), q(p.seo.description || ""), p.published, (i + 1) * 10].join(", ")})`).join(",\n"));
w("on conflict (path) do update set");
w("  label           = case when public.pages.label = '' then excluded.label else public.pages.label end,");
w("  seo_title       = case when public.pages.seo_title = '' then excluded.seo_title else public.pages.seo_title end,");
w("  seo_description = case when public.pages.seo_description = '' then excluded.seo_description else public.pages.seo_description end;");
w();
w("-- 7. FAQ categories --------------------------------------------------------");
w("insert into public.faq_categories (key, label, sort_order)");
w("values");
w(FAQ_CATEGORIES.map((c) => `  (${q(c.key)}, ${q(c.label)}, ${c.sort_order})`).join(",\n"));
w("on conflict (key) do nothing;");
w();
w("-- 8. FAQs: retire unedited legacy questions, add the documented 20 -------");
w("delete from public.faqs");
w(" where updated_at = created_at");
w(`   and question in (${legacyFaqs.map(q).join(",\n                    ")});`);
w();
w("insert into public.faqs (category_id, question, answer, is_active, show_on_home, sort_order)");
w("select c.id, v.question, v.answer, v.is_active, v.show_on_home, v.sort_order");
w("from (values");
w(FAQS.map((f) => `  (${[q(f.category), q(f.question), q(f.answer), f.is_active, f.show_on_home, f.sort_order].join(", ")})`).join(",\n"));
w(") as v(category, question, answer, is_active, show_on_home, sort_order)");
w("join public.faq_categories c on c.key = v.category");
w("where not exists (select 1 from public.faqs f where lower(trim(f.question)) = lower(trim(v.question)));");
w();
w("-- Empty legacy categories (no questions left) are switched off, not deleted.");
w("update public.faq_categories c set is_active = false");
w(` where c.key not in (${FAQ_CATEGORIES.map((c) => q(c.key)).join(", ")})`);
w("   and c.updated_at = c.created_at");
w("   and not exists (select 1 from public.faqs f where f.category_id = c.id);");
w();
w("-- 9. Services: documented card copy into blank fields --------------------");
for (const s of SERVICES) {
  w(`update public.services set`);
  w(`  title = case when title = '' then ${q(s.title)} else title end,`);
  w(`  summary = case when summary = '' then ${q(s.summary)} else summary end,`);
  w(`  cta_label = case when cta_label = '' then ${q(s.cta_label)} else cta_label end,`);
  w(`  image_url = case when image_url = '' then ${q(s.image_url)} else image_url end`);
  w(`where slug = ${q(s.slug)};`);
}
w("-- Unconfirmed services stay off the site until Siraj Builders confirms them");
w("-- (documentation: 'This page should remain unpublished until the service is confirmed').");
w(`update public.services set is_active = false, show_in_nav = false`);
w(` where slug in (${SERVICES.filter((s) => !s.confirmed).map((s) => q(s.slug)).join(", ")})`);
w("   and is_confirmed = false and updated_at = created_at;");
w();
w("-- 10. Settings added by this release ---------------------------------------");
w("insert into public.site_settings (key, value, display, is_confirmed, group_name, label, sort_order)");
w("values");
w(SETTINGS.map(([key, value, group, label, order]) => `  (${[q(key), q(value), q(""), true, q(group), q(label), order].join(", ")})`).join(",\n"));
w("on conflict (key) do nothing;");
w();
w("-- 11. Homepage: first hero slide uses the documented H1 -------------------");
w("update public.hero_slides");
w("   set eyebrow = 'Siraj Builders',");
w("       title = 'Construction, managed from the first plan to the final detail.',");
w("       lead = 'A well-built project begins long before construction starts. Siraj Builders brings together planning, coordination and on-site execution to create a more organised construction experience for homeowners, businesses and property investors.',");
w("       primary_label = 'Discuss Your Project', primary_to = '/consultation',");
w("       secondary_label = 'View Our Projects', secondary_to = '/projects'");
w(" where title = 'Built with clarity. Managed with care.'");
w("   and updated_at = created_at;");
w("-- A slide must not link to a service page that is not published yet.");
w("update public.hero_slides set primary_label = 'See How We Work', primary_to = '/our-process'");
w(" where primary_to = '/project-management' and updated_at = created_at;");
w();
w("commit;");
w();
w("notify pgrst, 'reload schema';");
w();
w("-- Final check: shows in the SQL editor's Messages tab");
w("do $$");
w("declare");
w("  n_sections int; n_pages int; n_faqs int; n_unanswered int;");
w("begin");
w("  select count(*) into n_sections from public.page_sections;");
w("  select count(distinct page_path) into n_pages from public.page_sections;");
w("  select count(*) into n_faqs from public.faqs;");
w("  select count(*) into n_unanswered from public.faqs where not is_active;");
w("  raise notice 'SIRAJ BUILDERS — content migration complete';");
w(`  raise notice '  page sections : % across % pages (documented: ${rows.length} across ${pages.length})', n_sections, n_pages;`);
w("  raise notice '  FAQs          : % (% waiting for an answer from Siraj Builders)', n_faqs, n_unanswered;");
w("end $$;");

fs.writeFileSync(path.join(__dirname, "migration-03-content.sql"), out.join("\n") + "\n");
console.log(`build-content: ${pages.length} pages, ${rows.length} sections, ${FAQS.length} FAQs, ${legacyPairs.length} legacy keys, ${legacyFaqs.length} legacy FAQs`);
