

insert into public.page_sections
  (page_path, page_label, section_key, label, section_type, title, body, settings, position, is_enabled)
values
('/residential-construction', 'Residential Construction', 'hero', 'Hero Section', 'hero', 'Page heading and intro', 'Eyebrow, title, intro paragraph and hero image.', '{"source":"pages","editor":"Pages"}'::jsonb, 0, true),
('/residential-construction', 'Residential Construction', 'body', 'Main Content', 'content', 'Main body', 'Heading, body copy and the bullet points beneath it.', '{"source":"pages","editor":"Pages"}'::jsonb, 1, true),
('/residential-construction', 'Residential Construction', 'detail', 'Secondary Content', 'content', 'Supporting band', 'The light band below the main content.', '{"source":"pages","editor":"Pages"}'::jsonb, 2, true),
('/residential-construction', 'Residential Construction', 'cta', 'CTA Section', 'cta', 'Closing call to action', 'The panel that invites the visitor to get in touch.', '{"source":"pages","editor":"Pages"}'::jsonb, 3, true),
('/renovation-remodelling', 'Renovation & Remodelling', 'hero', 'Hero Section', 'hero', 'Page heading and intro', 'Eyebrow, title, intro paragraph and hero image.', '{"source":"pages","editor":"Pages"}'::jsonb, 0, true),
('/renovation-remodelling', 'Renovation & Remodelling', 'body', 'Main Content', 'content', 'Main body', 'Heading, body copy and the bullet points beneath it.', '{"source":"pages","editor":"Pages"}'::jsonb, 1, true),
('/renovation-remodelling', 'Renovation & Remodelling', 'detail', 'Secondary Content', 'content', 'Supporting band', 'The light band below the main content.', '{"source":"pages","editor":"Pages"}'::jsonb, 2, true),
('/renovation-remodelling', 'Renovation & Remodelling', 'cta', 'CTA Section', 'cta', 'Closing call to action', 'The panel that invites the visitor to get in touch.', '{"source":"pages","editor":"Pages"}'::jsonb, 3, true),
('/design-architecture', 'Design & Architecture', 'hero', 'Hero Section', 'hero', 'Page heading and intro', 'Eyebrow, title, intro paragraph and hero image.', '{"source":"pages","editor":"Pages"}'::jsonb, 0, true),
('/design-architecture', 'Design & Architecture', 'body', 'Main Content', 'content', 'Main body', 'Heading, body copy and the bullet points beneath it.', '{"source":"pages","editor":"Pages"}'::jsonb, 1, true),
('/design-architecture', 'Design & Architecture', 'detail', 'Secondary Content', 'content', 'Supporting band', 'The light band below the main content.', '{"source":"pages","editor":"Pages"}'::jsonb, 2, true),
('/design-architecture', 'Design & Architecture', 'cta', 'CTA Section', 'cta', 'Closing call to action', 'The panel that invites the visitor to get in touch.', '{"source":"pages","editor":"Pages"}'::jsonb, 3, true),
('/grey-structure', 'Grey Structure', 'hero', 'Hero Section', 'hero', 'Page heading and intro', 'Eyebrow, title, intro paragraph and hero image.', '{"source":"pages","editor":"Pages"}'::jsonb, 0, true),
('/grey-structure', 'Grey Structure', 'body', 'Main Content', 'content', 'Main body', 'Heading, body copy and the bullet points beneath it.', '{"source":"pages","editor":"Pages"}'::jsonb, 1, true),
('/grey-structure', 'Grey Structure', 'detail', 'Secondary Content', 'content', 'Supporting band', 'The light band below the main content.', '{"source":"pages","editor":"Pages"}'::jsonb, 2, true),
('/grey-structure', 'Grey Structure', 'cta', 'CTA Section', 'cta', 'Closing call to action', 'The panel that invites the visitor to get in touch.', '{"source":"pages","editor":"Pages"}'::jsonb, 3, true),
('/turnkey-construction', 'Turnkey Construction', 'hero', 'Hero Section', 'hero', 'Page heading and intro', 'Eyebrow, title, intro paragraph and hero image.', '{"source":"pages","editor":"Pages"}'::jsonb, 0, true),
('/turnkey-construction', 'Turnkey Construction', 'body', 'Main Content', 'content', 'Main body', 'Heading, body copy and the bullet points beneath it.', '{"source":"pages","editor":"Pages"}'::jsonb, 1, true),
('/turnkey-construction', 'Turnkey Construction', 'detail', 'Secondary Content', 'content', 'Supporting band', 'The light band below the main content.', '{"source":"pages","editor":"Pages"}'::jsonb, 2, true),
('/turnkey-construction', 'Turnkey Construction', 'cta', 'CTA Section', 'cta', 'Closing call to action', 'The panel that invites the visitor to get in touch.', '{"source":"pages","editor":"Pages"}'::jsonb, 3, true),
('/project-management', 'Project Management', 'hero', 'Hero Section', 'hero', 'Page heading and intro', 'Eyebrow, title, intro paragraph and hero image.', '{"source":"pages","editor":"Pages"}'::jsonb, 0, true),
('/project-management', 'Project Management', 'body', 'Main Content', 'content', 'Main body', 'Heading, body copy and the bullet points beneath it.', '{"source":"pages","editor":"Pages"}'::jsonb, 1, true),
('/project-management', 'Project Management', 'detail', 'Secondary Content', 'content', 'Supporting band', 'The light band below the main content.', '{"source":"pages","editor":"Pages"}'::jsonb, 2, true),
('/project-management', 'Project Management', 'cta', 'CTA Section', 'cta', 'Closing call to action', 'The panel that invites the visitor to get in touch.', '{"source":"pages","editor":"Pages"}'::jsonb, 3, true),
('/leadership', 'Leadership', 'hero', 'Hero Section', 'hero', 'Page heading and intro', 'Eyebrow, title, intro paragraph and hero image.', '{"source":"pages","editor":"Pages"}'::jsonb, 0, true),
('/leadership', 'Leadership', 'body', 'Main Content', 'content', 'Main body', 'Heading, body copy and the bullet points beneath it.', '{"source":"pages","editor":"Pages"}'::jsonb, 1, true),
('/leadership', 'Leadership', 'detail', 'Secondary Content', 'content', 'Supporting band', 'The light band below the main content.', '{"source":"pages","editor":"Pages"}'::jsonb, 2, true),
('/leadership', 'Leadership', 'cta', 'CTA Section', 'cta', 'Closing call to action', 'The panel that invites the visitor to get in touch.', '{"source":"pages","editor":"Pages"}'::jsonb, 3, true),
('/locations', 'Locations', 'hero', 'Hero Section', 'hero', 'Page heading and intro', 'Eyebrow, title, intro paragraph and hero image.', '{"source":"pages","editor":"Pages"}'::jsonb, 0, true),
('/locations', 'Locations', 'body', 'Main Content', 'content', 'Main body', 'Heading, body copy and the bullet points beneath it.', '{"source":"pages","editor":"Pages"}'::jsonb, 1, true),
('/locations', 'Locations', 'detail', 'Secondary Content', 'content', 'Supporting band', 'The light band below the main content.', '{"source":"pages","editor":"Pages"}'::jsonb, 2, true),
('/locations', 'Locations', 'cta', 'CTA Section', 'cta', 'Closing call to action', 'The panel that invites the visitor to get in touch.', '{"source":"pages","editor":"Pages"}'::jsonb, 3, true),
('/international', 'International', 'hero', 'Hero Section', 'hero', 'Page heading and intro', 'Eyebrow, title, intro paragraph and hero image.', '{"source":"pages","editor":"Pages"}'::jsonb, 0, true),
('/international', 'International', 'body', 'Main Content', 'content', 'Main body', 'Heading, body copy and the bullet points beneath it.', '{"source":"pages","editor":"Pages"}'::jsonb, 1, true),
('/international', 'International', 'detail', 'Secondary Content', 'content', 'Supporting band', 'The light band below the main content.', '{"source":"pages","editor":"Pages"}'::jsonb, 2, true),
('/international', 'International', 'cta', 'CTA Section', 'cta', 'Closing call to action', 'The panel that invites the visitor to get in touch.', '{"source":"pages","editor":"Pages"}'::jsonb, 3, true),
('/subcontractors', 'Subcontractors', 'hero', 'Hero Section', 'hero', 'Page heading and intro', 'Eyebrow, title, intro paragraph and hero image.', '{"source":"pages","editor":"Pages"}'::jsonb, 0, true),
('/subcontractors', 'Subcontractors', 'body', 'Main Content', 'content', 'Main body', 'Heading, body copy and the bullet points beneath it.', '{"source":"pages","editor":"Pages"}'::jsonb, 1, true),
('/subcontractors', 'Subcontractors', 'detail', 'Secondary Content', 'content', 'Supporting band', 'The light band below the main content.', '{"source":"pages","editor":"Pages"}'::jsonb, 2, true),
('/subcontractors', 'Subcontractors', 'cta', 'CTA Section', 'cta', 'Closing call to action', 'The panel that invites the visitor to get in touch.', '{"source":"pages","editor":"Pages"}'::jsonb, 3, true),
('/role-definition', 'Role Definition', 'hero', 'Hero Section', 'hero', 'Page heading and intro', 'Eyebrow, title, intro paragraph and hero image.', '{"source":"pages","editor":"Pages"}'::jsonb, 0, true),
('/role-definition', 'Role Definition', 'body', 'Main Content', 'content', 'Main body', 'Heading, body copy and the bullet points beneath it.', '{"source":"pages","editor":"Pages"}'::jsonb, 1, true),
('/role-definition', 'Role Definition', 'detail', 'Secondary Content', 'content', 'Supporting band', 'The light band below the main content.', '{"source":"pages","editor":"Pages"}'::jsonb, 2, true),
('/role-definition', 'Role Definition', 'cta', 'CTA Section', 'cta', 'Closing call to action', 'The panel that invites the visitor to get in touch.', '{"source":"pages","editor":"Pages"}'::jsonb, 3, true),
('/cost-index', 'Cost Index', 'hero', 'Hero Section', 'hero', 'Page heading and intro', 'Eyebrow, title, intro paragraph and hero image.', '{"source":"pages","editor":"Pages"}'::jsonb, 0, true),
('/cost-index', 'Cost Index', 'body', 'Main Content', 'content', 'Main body', 'Heading, body copy and the bullet points beneath it.', '{"source":"pages","editor":"Pages"}'::jsonb, 1, true),
('/cost-index', 'Cost Index', 'detail', 'Secondary Content', 'content', 'Supporting band', 'The light band below the main content.', '{"source":"pages","editor":"Pages"}'::jsonb, 2, true),
('/cost-index', 'Cost Index', 'cta', 'CTA Section', 'cta', 'Closing call to action', 'The panel that invites the visitor to get in touch.', '{"source":"pages","editor":"Pages"}'::jsonb, 3, true),
('/project-showcase', 'Project Showcase', 'hero', 'Hero Section', 'hero', 'Page heading and intro', 'Eyebrow, title, intro paragraph and hero image.', '{"source":"pages","editor":"Pages"}'::jsonb, 0, true),
('/project-showcase', 'Project Showcase', 'body', 'Main Content', 'content', 'Main body', 'Heading, body copy and the bullet points beneath it.', '{"source":"pages","editor":"Pages"}'::jsonb, 1, true),
('/project-showcase', 'Project Showcase', 'detail', 'Secondary Content', 'content', 'Supporting band', 'The light band below the main content.', '{"source":"pages","editor":"Pages"}'::jsonb, 2, true),
('/project-showcase', 'Project Showcase', 'cta', 'CTA Section', 'cta', 'Closing call to action', 'The panel that invites the visitor to get in touch.', '{"source":"pages","editor":"Pages"}'::jsonb, 3, true),
('/commercial-construction', 'Commercial Construction', 'hero', 'Hero Section', 'hero', '', '', '{"source":"page","editor":"code"}'::jsonb, 0, true),
('/commercial-construction', 'Commercial Construction', 'approach', 'Our Approach', 'content', '', '', '{"source":"page","editor":"code"}'::jsonb, 1, true),
('/commercial-construction', 'Commercial Construction', 'focus', 'Focus Areas', 'content', '', '', '{"source":"page","editor":"code"}'::jsonb, 2, true),
('/commercial-construction', 'Commercial Construction', 'proof', 'Proof / Projects', 'projects', '', '', '{"source":"page","editor":"code"}'::jsonb, 3, true),
('/commercial-construction', 'Commercial Construction', 'cta', 'CTA Banner', 'cta', '', '', '{"source":"page","editor":"code"}'::jsonb, 4, true),
('/affiliates', 'Affiliates', 'hero', 'Hero Section', 'hero', '', '', '{"source":"page","editor":"code"}'::jsonb, 0, true),
('/affiliates', 'Affiliates', 'intro', 'Introduction', 'intro', '', '', '{"source":"page","editor":"code"}'::jsonb, 1, true),
('/affiliates', 'Affiliates', 'partners', 'Partner Network', 'content', '', '', '{"source":"page","editor":"code"}'::jsonb, 2, true),
('/affiliates', 'Affiliates', 'standards', 'Standards', 'content', '', '', '{"source":"page","editor":"code"}'::jsonb, 3, true),
('/affiliates', 'Affiliates', 'cta', 'CTA Banner', 'cta', '', '', '{"source":"page","editor":"code"}'::jsonb, 4, true)
on conflict (page_path, section_key) do nothing;
