/* eslint-disable */
/**
 * ENV BRIDGE
 * ============================================================================
 * This project is Create React App, not Vite. CRA's build only injects
 * variables prefixed `REACT_APP_` into the bundle — anything else is stripped
 * and arrives as `undefined` at runtime.
 *
 * Rather than make that your problem, this script runs automatically before
 * `npm run dev`, `npm start` and `npm run build`. It reads `.env` and, for any
 * `VITE_SUPABASE_*` variable it finds, writes the matching `REACT_APP_*` into
 * `.env.local` so the value actually reaches the app.
 *
 * So both of these work. Use whichever you already have:
 *
 *   VITE_SUPABASE_URL=https://xxxx.supabase.co
 *   REACT_APP_SUPABASE_URL=https://xxxx.supabase.co
 *
 * Node's standard library only — nothing to install.
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const ENV_FILE = path.join(ROOT, ".env");
const LOCAL_FILE = path.join(ROOT, ".env.local");

const MAP = {
  VITE_SUPABASE_URL: "REACT_APP_SUPABASE_URL",
  VITE_SUPABASE_ANON_KEY: "REACT_APP_SUPABASE_ANON_KEY",
};

function parse(file) {
  if (!fs.existsSync(file)) return {};
  const out = {};
  for (const raw of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    // Strip surrounding quotes if present.
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

function main() {
  const env = parse(ENV_FILE);
  const existingLocal = parse(LOCAL_FILE);
  const bridged = {};

  for (const [viteKey, craKey] of Object.entries(MAP)) {
    // Only bridge when the VITE_ name has a value and the CRA name does not
    // already have one — a real REACT_APP_ value always wins.
    const craValue = env[craKey] || existingLocal[craKey];
    if (env[viteKey] && !craValue) bridged[craKey] = env[viteKey];
  }

  if (!Object.keys(bridged).length) return;

  const merged = { ...existingLocal, ...bridged };
  const body =
    "# Generated by scripts/env-bridge.js — do not edit by hand.\n" +
    "# Source of truth is .env\n" +
    Object.entries(merged)
      .map(([k, v]) => `${k}=${v}`)
      .join("\n") +
    "\n";

  fs.writeFileSync(LOCAL_FILE, body);
  console.log(
    `[env-bridge] Mapped ${Object.keys(bridged).join(", ")} from .env → .env.local`
  );
}

try {
  main();
} catch (error) {
  // Never block the dev server over this.
  console.warn("[env-bridge] Skipped:", error.message);
}
